### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by eksekjut** [ZeroDiscord/Giveaway#50]
**Describe the bug**
Bot will crash everytime someone does (prefix)edit and types a letter.

**To Reproduce**
1. Type command edit
2. Reply with letter or sentance
3. Boom crashed with errors
4. Here is Error:
/home/runner/Giveaway/commands/edit.js:43
    let gid = BigInt(response).toString()
              ^

SyntaxError: Cannot convert g!edit 1067505712705576960 to a BigInt
    at BigInt (<anonymous>)
    at MessageCollector.<anonymous> (/home/runner/Giveaway/commands/edit.js:43:15)
    at MessageCollector.emit (node:events:513:28)
    at MessageCollector.handleCollect (/home/runner/Giveaway/node_modules/discord.js/src/structures/interfaces/Collector.js:119:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
exit status 1

I expected it will give me message needs to be ID or make it so it works for last giveaway made which is much better.

**Screenshots**
![image](https://user-images.githubusercontent.com/81157619/214373897-0030f6c8-e5d3-4e32-ba18-8e511c7935da.png)

There is more errors just I will find I am 99% sure, contact me on discord where I can tell you instantly! (yng1ne#7126)

**Comment by ZeroDiscord** [comment]
Fixed as per https://github.com/ZeroDiscord/Giveaway/commit/d8b04b5d779488e5abae8d0ec2d44f1dd993b1dc
