### ISSUE TITLE
User blocked the bot

### ISSUE THREAD

**Issue by ElTuna** [ZeroDiscord/Giveaway#6]
When a user that blocked the bot reacts to the giveaway... the bot crashes with this error.
```
/root/bots/sorteos/node_modules/discord.js/src/rest/RequestHandler.js:349
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Reaction blocked
    at RequestHandler.execute (/root/bots/sorteos/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/bots/sorteos/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async MessageManager.react (/root/bots/sorteos/node_modules/discord.js/src/managers/MessageManager.js:193:5)
    at async Message.react (/root/bots/sorteos/node_modules/discord.js/src/structures/Message.js:720:5) {
  method: 'put',
  path: '/channels/904338272795369472/messages/904773949395697694/reactions/%E2%9C%85/@me',
  code: 90001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}```

**Comment by ZeroDiscord** [comment]
Fixed as of - https://github.com/ZeroDiscord/Giveaway/commit/ec19fbeb3e1612f9e18ff55c9fa23b6fee7b5a51
Thanks for reporting!
